// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgrY_b_21u2ShuxvezaHmYnz1mfX7Qjbo',
    appId: '1:989967220501:web:8ce8b2c58b06c8767cf31c',
    messagingSenderId: '989967220501',
    projectId: 'laza-6588a',
    authDomain: 'laza-6588a.firebaseapp.com',
    storageBucket: 'laza-6588a.appspot.com',
    measurementId: 'G-2QQ03F3TGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD0esgnG_KyEhPKP5lQaps4Dx7hzAJz2w',
    appId: '1:989967220501:android:8a211663718c22627cf31c',
    messagingSenderId: '989967220501',
    projectId: 'laza-6588a',
    storageBucket: 'laza-6588a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASIEdnfyw3uxGkXGAiysJ3gr5nNBGtdA4',
    appId: '1:989967220501:ios:9e318eaaf29a57687cf31c',
    messagingSenderId: '989967220501',
    projectId: 'laza-6588a',
    storageBucket: 'laza-6588a.appspot.com',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASIEdnfyw3uxGkXGAiysJ3gr5nNBGtdA4',
    appId: '1:989967220501:ios:2e0a39bdac9d0ebe7cf31c',
    messagingSenderId: '989967220501',
    projectId: 'laza-6588a',
    storageBucket: 'laza-6588a.appspot.com',
    iosBundleId: 'com.example.laza.RunnerTests',
  );
}
